server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    # Uses host.docker.internal so it connects directly to your Windows MySQL
    url: jdbc:mysql://${DB_HOST:host.docker.internal}:3306/user_service_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      # Connects to eureka-server container on the Docker network
      defaultZone: http://${EUREKA_HOST:eureka-server}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: MyVeryStrongSecretKeyForJwtAuthentication123456789