pipeline {
    agent any
    environment {
        DOCKER_NETWORK = 'banking-network'
        PATH = "C:\\Users\\user\\AppData\\Local\\Programs\\DockerDesktop\\resources\\bin;${env.PATH}"
    }
    stages {
        stage('Checkout') { steps { checkout scm } }
        stage('Build') {
            steps {
                dir('microservices') { bat 'mvn clean package -DskipTests -pl eureka-server -am' }
            }
        }
        stage('Deploy Container') {
            steps {
                dir('microservices/eureka-server') {
                    bat 'docker network create %DOCKER_NETWORK% || exit 0'
                    bat 'docker build -t eureka-server:latest .'
                    bat 'docker stop eureka-server || exit 0'
                    bat 'docker rm eureka-server || exit 0'
                    bat 'docker run -d --name eureka-server --net %DOCKER_NETWORK% -p 8761:8761 eureka-server:latest'
                }
            }
        }
    }
}